# fly.toml app configuration file generated for agfactory-web
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agfactory-web'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.web'

[env]
  PORT = '8080'

# Persistent storage for agents
[mounts]
  source = 'agfactory_data'
  destination = '/app/agents'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Keep WebSocket connections alive during long-running operations
  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  # Increase idle timeout for WebSocket connections
  [http_service.http_options]
    idle_timeout = "60s"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

