# fly.toml app configuration file generated for agfactory-web on 2025-10-12T10:50:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agfactory-web'
primary_region = 'sjc'

[build]
  dockerfile = '../Dockerfile.web'
  build-target = ""

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
